# Generated by Django 4.2.9 on 2024-01-14 12:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Employee",
            fields=[
                ("Employee_id", models.IntegerField(primary_key=True, serialize=False)),
                ("Employee_name", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="Departments",
            fields=[
                (
                    "Department_id",
                    models.IntegerField(primary_key=True, serialize=False),
                ),
                ("Department_name", models.CharField(max_length=50)),
                (
                    "Department_manager",
                    models.OneToOneField(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="manager",
                        to="home.employee",
                    ),
                ),
            ],
        ),
    ]
