# Generated by Django 4.2.9 on 2024-01-14 21:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="departments",
            name="Department_manager",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="manager",
                to="home.employee",
            ),
        ),
    ]
